### ISSUE TITLE
Cycle accurate implementation

### ISSUE THREAD

**Issue by bombela** [pusherofbrooms/avr-delay#23]
I am looking at implementing a cycle accurate solution. Pretty much identical to what the gcc-avr intrinsic does.
This was discussed in #17. Here is the code for reference: https://gist.github.com/bombela/cc90e5c29f3e7667326de4c087c1e148.

At the time of writing this, the implementation on `master` and `rewrite` are both not guaranteed to be expanded at compile time, and they are also not accurate.

Before I spend anytime working in this PR, I would like to know if you are interested in it. And if I should raise it against the `rewrite` branch.

**Comment by stappersg** [comment]
Against branch `cycacc`,  that is currently equal to `master` branch.

Yes, do read that as _there is interest in a cycle accurate solution_.  It is the _pretty much identical to what the GCC-AVR intrinsic does_ what makes it appealling.

Branch `rewrite` was created for finding out _"what is the actual change?"_, name is based on title **"Rewrote library to fix several issues"** of #17.    Some how it does feel like _"rewrite just because we can"_,  I prefer _"change for a reason"_.

**Comment by bombela** [comment]
Ok!
